# Using the Wacom for screen capture

For recording screen captures of video tutorials or coding examples, the Wacom tablet located in the middle of the room on the left wall is the best device to use. 

The Wacom is a large tablet device which can be used for written tutorials, similarly to an iPad. The Wacom is connected to the nearby Windows machine which should be switched on. You can log in using your GUID. 

## Setting up screen capture

- To capture your active screen on the Wacom, you can use OBS Studio which is located on the desktop. 

- Once OBS Studio is open, select the Wacom display from the display options to capture this screen (you can drag any additional open windows over to the monitor on the Windows machine). For the video settings, set the video resolution to 1280 x 1024 for base and output. 

- For the file type, save this as a .flv file. This will be converted on the Mac.

- Set your file path to the desired location (Videos is often the default).

- For the display capture, to ensure that the Wacom is available, you may need to add in the source. This can be done by selecting Sources and "Add display capture", then adding Display 1. 

- Once set up, OBS Studio will start recording your screen once you press record. Ensure you have everything you wish to record active on the Wacom, and remove any additional windows. Mute any desktop sounds.

- Sound recording can be performed using either the headset or the microphone beside the Windows machine. 


## Using SmoothDraw for tutorial videos

- To produce written tutorial style videos, the programme SmoothDraw provides a nice interface to produce Khan Academy style tutorial videos. SmoothDraw can be found on the Desktop. If this is not visible, you can search for the application in the Start bar. 

- To ensure the full drawing palette is selected by the video, you will have to resize the palette. This can be done by selecting File > Resize. Untick both the width/height ratio options and set these to 1280 x 1024. 
- OBS Studio will show which area of the screen will be captured prior to recording, you can align SmoothDraw to fit within this window. 

- You may find it useful to change the palette colour to black (similarly to ODL tutorial videos) which can be changed in the "Background" layer option. 

- To set up writing, it is best to select the pen option for writing. You can set up shortcut keys for different colours, which can be useful for highlighting. 

- To show additional steps within a problem, you can use layers. On the left tab under Layers, you can "select new layer" which will create a new layer over the current palette to add new steps. Once these steps are shown, you can remove the layer by highlighting the new layer on the pane and pressing delete. 


## Editing the recording

- Once you have finished your recording, you can edit this in Final Cut using the Mac. 

- Transfer your recording to the Mac (either using a USB or transferring the file via OneDrive or a shared folder).

- With your video recording, you will first have to change this to mp4 for editing. This can be performed using HandBrake which can transcode your video. 

- Open HandBrake (this can be found in the Dock). Once open, load your video file(s) by clicking on "Source" where you can select your videos for conversion. 

- Next, select your output format from the menu that appears. Select mp4. 

- You will have to ensure the picture resolution is correct. This can be checked by clicking the "Picture Settings" tab on the menu and ensuring this is set to 1280 x 1024). 

- The sound from your video may be quiet. You can check this prior to converting. If so, you can boost the sound by selecting the Audio tab on the menu and increasing the Gain (this can also be edited in Final Cut, so feel free to do this there).

- Once all settings have been checked, convert the video by pressing the "Start" button, which will begin the conversion. 

- A pop-up will appear in the top right corner once this has been completed. You can then use your .mp4 video in Final Cut for editing.
